#!/bin/csh -f

rm -rf MyDbTest
exec java -jar ./derbyrun.jar ij <<EOF
connect 'jdbc:derby://localhost:3308/MyDbTest;create=true';
CALL SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY(
    'derby.connection.requireAuthentication',
    'true');
CALL SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY(
    'derby.user.MyDbTestUser', 'MyDbTestPasswd');
CALL SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY(
    'derby.database.fullAccessUsers', 'MyDbTestUser');
create schema DEVELOPMENT AUTHORIZATION MYDBTESTUSER;
--create table MyDbTest.Student (
--   Id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
--   Age INT NOT NULL,
--   First_Name VARCHAR(255),
--   last_name VARCHAR(255),
--   PRIMARY KEY (Id)
--);
--grant ALL PRIVILEGES ON MyDbTest.Student TO MyDbTestUser ;
exit;
EOF
