#!/bin/csh -f

rm -rf MyDbTest
exec java -jar ./derbyrun.jar ij <<EOF
connect 'jdbc:derby://localhost:3308/MyDbTest' USER 'MyDbTestUser' PASSWORD 'MyDbTestPasswd' ;
show tables;
set schema DEVELOPMENT;
select * from TEACHERS;
select * from STUDENTS;
exit;
EOF
