#!/bin/csh -f

rm -f derby.log
if (! -d dbase) mkdir dbase
source ./common.csh
exec java -Dderby.system.home=$PWD/dbase -Dderby.database.sqlAuthorization=true -jar ./derbyrun.jar server start -h $host -p $port
